title: Vijay kumar Manda
logo: /assets/img/VijayPhoto.png
description: I'm Learning on Data Science & Machine Learning in iit-Bengalore through Upgrad.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
