
  
title: <p align="center">Arun Prakash </p>
logo: /assets/img/Screenshot%202022-12-26%20at%2000.42.31.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
