title: <p align="center"> Abhishek Singh </p>
logo: /assets/img/logo.png

description:
  <p align="center"> | |
  <a href="https://github.com/Abhisheksingh115">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
