title: <p align="center"> Vinodh Nagarajaiah </p>
logo: /assets/img/logo.jpeg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vinodh-n-5914874b/">LinkedIn</a> |
  <a href="https://github.com/techexorcist">GitHub</a>
  
  <br>   
  I'm working technical side of things that majorly involves coding in Java, Scala, GoLang or in pythin based on 
  project requirements. I am also certified kubernetes developer with amople experience in handling CI/CD pipelines.
  Currently working for a cybersecurity company.
  <br>
  </p>



theme: jekyll-theme-minimal