title: <p align="center"> Sahana C </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  
  <br>   
  I'm working as a Automation Test Engineer.
  Working with Capgemini on Semiconductor project to 
  handle functional testing on Bluetooth Profile with Android.
  <br>
  </p>



theme: jekyll-theme-minimal