title: <p align="center"> Sankar Ashokkumar </p>
logo: /assets/img/Sankar_Image.jpg
description:  
<p align="center">
<br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
