title: Dr Stephen McAteer
logo: /assets/img/logo.png
description: Personal homepage of Steve McAteer, record of projects, presentations and publications.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
