title: <p align = "center">Raghavendra </p>
       <p align = "center">Srinivasan</p>
logo: /assets/img/raghavendra.jpg
description: 
A result-oriented Professional with 1.5+ years of experience and extensive knowledge of programming. Currently seeking to apply my analytical skills with strong apt for learning and collaborative skills along with statistical and Machine Learning concepts to prove a highly valuable asset for the organization.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
